"""Add must_change_password and anio_en_curso

Revision ID: 0dd7c8477afb
Revises: 90e20021f301
Create Date: 2026-07-18 19:12:15.237957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd7c8477afb'
down_revision: Union[str, None] = '90e20021f301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnos', sa.Column('anio_en_curso', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    op.drop_column('alumnos', 'anio_en_curso')
    # ### end Alembic commands ###
