"""add_camaras_and_eventos_acceso

Revision ID: 66ea364a9422
Revises: 48000b47d7a0
Create Date: 2026-05-30 20:11:15.092585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ea364a9422'
down_revision: Union[str, None] = '48000b47d7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camaras',
    sa.Column('id_camara', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_camara')
    )
    op.create_table('eventos_acceso',
    sa.Column('id_evento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camara_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('confianza_ia', sa.Float(), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camara_id'], ['camaras.id_camara'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['Persona.id_persona'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos_acceso')
    op.drop_table('camaras')
    # ### end Alembic commands ###
