"""add stream_url to camaras

Revision ID: 80ede6450cf3
Revises: b2c3d4e5f608
Create Date: 2026-09-23 09:00:42.357743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ede6450cf3'
down_revision: Union[str, None] = 'b2c3d4e5f608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - ajustado a solo stream_url ###
    op.add_column('camaras', sa.Column('stream_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - ajustado a solo stream_url ###
    op.drop_column('camaras', 'stream_url')
    # ### end Alembic commands ###
