"""add_lectura_rfid

Revision ID: 84086fcf91c4
Revises: 1d1724f8e28e
Create Date: 2026-05-28 10:25:32.385061

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '84086fcf91c4'
down_revision: Union[str, None] = '1d1724f8e28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lectura_rfid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_rfid', sa.String(length=100), nullable=False),
    sa.Column('id_computadoras', sa.Integer(), nullable=True),
    sa.Column('lector_origen', sa.String(length=100), nullable=True),
    sa.Column(
        'timestamp', sa.DateTime(timezone=True),
        server_default=sa.text('now()'), nullable=False,
    ),
    sa.ForeignKeyConstraint(['id_computadoras'], ['Computadoras.id_computadoras'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lectura_rfid_tag_rfid'), 'lectura_rfid', ['tag_rfid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_lectura_rfid_tag_rfid'), table_name='lectura_rfid')
    op.drop_table('lectura_rfid')
    # ### end Alembic commands ###
