"""add_rfid_tables

Revision ID: 90e20021f301
Revises: 66ea364a9422
Create Date: 2026-06-22 11:25:13.567116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90e20021f301'
down_revision: Union[str, None] = '66ea364a9422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfid_lectores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfid_eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_rfid', sa.String(length=100), nullable=False),
    sa.Column('lector_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('detalles', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lector_id'], ['rfid_lectores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfid_eventos_tag_rfid'), 'rfid_eventos', ['tag_rfid'], unique=False)
    op.create_table('rfid_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_rfid', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('id_computadoras', sa.Integer(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_computadoras'], ['Computadoras.id_computadoras'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfid_tags_tag_rfid'), 'rfid_tags', ['tag_rfid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfid_tags_tag_rfid'), table_name='rfid_tags')
    op.drop_table('rfid_tags')
    op.drop_index(op.f('ix_rfid_eventos_tag_rfid'), table_name='rfid_eventos')
    op.drop_table('rfid_eventos')
    op.drop_table('rfid_lectores')
    # ### end Alembic commands ###
